### ISSUE TITLE
error when call org-toggle-inline-images

### ISSUE THREAD

**Issue by DarkBuffalo** [konstare/emacs-gcc-pgtk#1]
when we call `org-toggle-inline-images` no image appears.

**Comment by konstare** [comment]
Could you show `emacs-version` ? 
I am using emacs which is built 2021-04-06 and `org-toggle-inline-images` works for me.

**Comment by DarkBuffalo** [comment]
Yes
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2021-04-08`

**Comment by konstare** [comment]
I have updated emacs to "2021-04-08 build", still everything works fine. Do you have any suspicious lines in the buffer *Messages*?

**Comment by DarkBuffalo** [comment]
Sorry, the cause of the problem is: `#+attr_latex: :width 5cm`
Thanks for the help. Nice Job.
